# Generated by Django 5.2.7 on 2025-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitshowcase', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='forks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='stargazers_count',
            field=models.IntegerField(default=0),
        ),
    ]
